version: '3'

services:

    # ------ WEB APPLICATION BLOCK ------ 

    web_app:
        container_name: web_app
        build:
            context: ./services/web_app/
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./services/web_app/:/var/www/
        links:
            - db_server:db_server
        depends_on:
            - db_server
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db_server
            DB_PORT: 3306
            DB_DATABASE: docker
            DB_USERNAME: docker
            DB_PASSWORD: 123456789
        networks:
            - docker-network

    web_server:
        container_name: web_server
        build:
            context: ./services/web_server/
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./services/web_app/public/:/var/www/public/
        links:
            - web_app:web_app
        ports:
            - 9900:80
        networks:
            - docker-network

    # ------ DATABASE BLOCK ------ 

    db_server:
        container_name: db_server
        image: mysql:8.0.15
        restart: always
        command:
            - "--default-authentication-plugin=mysql_native_password"
        environment:
            TERM: linux
            LANG: "C.UTF-8"
            MYSQL_USER: docker
            MYSQL_PASSWORD: 123456789
            MYSQL_DATABASE: docker
            MYSQL_ROOT_PASSWORD: root
        networks:
            - docker-network

    db_adminer:
        container_name: adminer
        image: adminer:4.7.1
        ports:
            - 9901:8080
        restart: always
        depends_on:
            - db_server
        networks:
            - docker-network

networks:
    docker-network:
        driver: bridge
